accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('author/<str:username>/', views.user_profile, name='profile'),
    # login / logout urls
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('signup/', views.signup_user, name="signup"),
    path('edit/', views.edit, name='edit'),
    path('404/', views.custom_404, name="404"),
    path('password-change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password-reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path('', views.articles_list, name='articles_list'),
    path('tag/<slug:tag_slug>/', views.articles_list, name='articles_list_by_tag'),
    # path('add-like/<int:pk>/', views.add_like, name='add_like'),
    path('books', views.books, name='books'),
    path('article/<slug:article_id>/like', views.like_article, name="like"),
    path('all-articles/', views.all_articles, name='all_articles'),
    path('create-article/', views.create_articles, name='create_article'),
    path('update-article/<int:pk>/', views.update_articles, name='update_article'),
    path('<int:year>/<int:month>/<int:day>/<slug:article>/', views.articles_detail, name='articles_detail'),
    path('<int:article_id>/share/', views.article_share, name='article_share'),
    path('<int:article_id>/comment/', views.article_comment, name='article_comment'),
    path('delete-article/<int:pk>/', views.delete_articles, name='delete_articles'),
]

narrative_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from articles.sitemaps import ArticleSitemap

sitemaps = {
    'articles': ArticleSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls', namespace='articles')),
    path('accounts/', include('accounts.urls')),
    path('inspiration/', include('inspiration.urls', namespace='inspiration')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
    ]

templates/includes/comment_form.html
{% load static %}

<form action="{% url 'articles:article_comment' article.id %}" method="POST" class="comment-box">
  <div class="user">
    <div class="image">
      <img src="{% static '/images/Asaiah Henson.jpg' %}" alt="" />
    </div>
    <div class="name"><span>Asaiah Henson</span></div>
  </div>
  {{ form.as_p }}
   {% csrf_token %}
  <button type="submit" class="comment-submit">Post Comment</button>
</form>

templates/includes/pagination.html
<nav aria-label="Page navigation example">
  <ul class="pagination">
      {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
    {% endif %}
    <li class="page-item"><a class="page-link" href="#">{{ page.number }} of {{ page.paginator.num_pages }}</a></li>
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>