accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('author/<str:username>/', views.user_profile, name='profile'),
    # login / logout urls
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('signup/', views.signup_user, name="signup"),
    path('edit/', views.edit, name='edit'),
    path('404/', views.custom_404, name="404"),
    path('password-change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password-reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path('', views.articles_list, name='articles_list'),
    path('tag/<slug:tag_slug>/', views.articles_list, name='articles_list_by_tag'),
    # path('add-like/<int:pk>/', views.add_like, name='add_like'),
    path('books', views.books, name='books'),
    path('article/<slug:article_id>/like', views.like_article, name="like"),
    path('all-articles/', views.all_articles, name='all_articles'),
    path('create-article/', views.create_articles, name='create_article'),
    path('update-article/<int:pk>/', views.update_articles, name='update_article'),
    path('<int:year>/<int:month>/<int:day>/<slug:article>/', views.articles_detail, name='articles_detail'),
    path('<int:article_id>/share/', views.article_share, name='article_share'),
    path('<int:article_id>/comment/', views.article_comment, name='article_comment'),
    path('delete-article/<int:pk>/', views.delete_articles, name='delete_articles'),
]

inspiration/urls.py
from django.urls import path
from .import views

app_name='inspiration'

urlpatterns = [
    path('inspiration/', views.inspiration, name='inspiration'),
    # path('inspiration-detail/', views.inspiration_detail, name='inspiration_detail')
]

narrative_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from articles.sitemaps import ArticleSitemap

sitemaps = {
    'articles': ArticleSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls', namespace='articles')),
    path('accounts/', include('accounts.urls')),
    path('inspiration/', include('inspiration.urls', namespace='inspiration')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
    ]

articles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager
from django_ckeditor_5.fields import CKEditor5Field
from django.utils.text import slugify
# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Articles.Status.PUBLISHED)
    
class DraftManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Articles.Status.DRAFT)

# class Author(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     bio = models.TextField()

#     def __str__(self):
#         return self.user.username
    
class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"
    def __str__(self):
        return self.name

class Articles(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    content = CKEditor5Field('content', config_name='extends')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    categories = models.ManyToManyField(Category)
    publish = models.DateTimeField(default=timezone.now)
    likes = models.ManyToManyField(User, related_name='likedposts', through="LikedPost")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='article_images/')
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)
    objects = models.Manager()
    published = PublishedManager()
    draft = DraftManager()
    tags = TaggableManager()
    
    class Meta:
        ordering = ['-publish']
        verbose_name = 'Article'
        verbose_name_plural = 'Articles'
        indexes = [
            models.Index(fields=['-publish']),
            ]
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)
        
    def __str__(self):
        return f"{self.title} by {self.author}"
    
    def get_absolute_url(self):
        return reverse('articles:articles_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])

class LikedPost(models.Model):
    article = models.ForeignKey(Articles, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    
class Comment(models.Model):
    article = models.ForeignKey(Articles, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    class Meta:
        ordering = ['created']
        indexes = [
        models.Index(fields=['created']),
        ]
    def __str__(self):
        return f'Comment by {self.name} on {self.article}'
    

    
    

inspiration/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

# Create your models here.

class Inspiration(models.Model):
    language = (
        ('HTML', 'HTML'),
        ('CSS', 'CSS'),
        ('Python', 'Python'),
        ('Java scripts', 'Java scripts'),
        ('Java', 'Java'),
        ('Kotlin', 'Kotlin'),
        ('C++', 'C++'),
        ('C#', 'C#'),
        ('Ruby', 'Ruby'),
        ('Swift', 'Swift'),
        ('Solidity', 'Solidity'),
        ('Dart', 'Dart'),
    ) 
    title = models.CharField(max_length=100)
    builder = models.ForeignKey(User, on_delete=models.CASCADE)
    source_code = models.CharField(max_length=100)
    slug = models.SlugField(max_length=250)
    live_demo = models.CharField(max_length=50)
    description = models.TextField()
    programmingLg = models.CharField(max_length=25, choices=language)
    image = models.ImageField(upload_to='inspiration_images/')
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
            ]
        
    def get_absolute_url(self):
        return reverse('inspiration:inspiration_detail', args=[self.slug])
    
    
    def __str__(self):
        return self.title

articles/forms.py
from django import forms
from .models import Comment, Articles


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=30)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)
    
    
class CommentForm(forms.ModelForm):
    # def __init__(self, *args, **kwargs):
    #       super().__init__(*args, **kwargs)
    #       self.fields["text"].required = False
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']
    
        
class ArticlesForm(forms.ModelForm):
    class Meta:
        model = Articles
        fields = ['title', 'content', 'categories', 'image', 'tags', 'status']
        
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     if self.instance.pk:
    #         self.fields['author'].initial = self.instance.author.username
    #     else:
    #         self.fields['author'].initial = kwargs.get('author', '')
    #         if not self.fields['author'].initial:
    #             self.fields['author'].initial = request.user.username

    #     # Update this line
    #     self.fields['author'].initial = self.fields['author'].initial or request.user.username
        
class SearchBook(forms.Form):
    text = forms.CharField(max_length=100)

articles/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Articles, Comment
from .forms import SearchBook
# from accounts.models import Profile
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostForm, CommentForm, ArticlesForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.contrib.auth.decorators import login_required
from .filters import ArticlesFilter
from django.contrib import messages
from django.db.models import Count
from django.http import JsonResponse
import requests
from googleapiclient.discovery import build

# Create your views here.

def articles_list(request):
    articles = Articles.published.all()
    context = {
        'articles':articles,
    }
    return render(request, 'articles/article-list.html', context)

@login_required
def all_articles(request, tag_slug=None):
    article_filter = ArticlesFilter(request.GET, queryset=Articles.published.all())
    articles = article_filter.qs
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        articles_list = articles.filter(tags__in=[tag])
    # Pagination with 3 posts per page
    paginator = Paginator(articles, 5)
    page_number = request.GET.get('page', 1)
    try:
        articles = paginator.page(page_number)
    except PageNotAnInteger:
    # If page_number is not an integer deliver the first page
        articles = paginator.page(1)
    except EmptyPage:
        # If page_number is out of range deliver last page of results
        articles = paginator.page(paginator.num_pages)

    context = {
        'tag':tag,
        'filter': article_filter, 
        'articles': articles
    }
    return render(request, 'articles/all_articles.html', context)

@login_required
def articles_detail(request, year, month, day, article):
    article = get_object_or_404(Articles, slug=article, status=Articles.Status.PUBLISHED, publish__year=year, publish__month=month, publish__day=day)
    # List of active comments for this post
    comments = article.comments.filter(active=True)[:2]
    # # Form for users to comment
    form = CommentForm()
    # author = article.author
    # profile = author.profile if author.profile else None
    
    # List of similar posts
    article_tags_ids = article.tags.values_list('id', flat=True)
    similar_articles = Articles.published.filter(tags__in=article_tags_ids).exclude(id=article.id)
    similar_articles = similar_articles.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:2]
    context = {
        'article': article,
        'comments': comments, 
        'form':form, 
        'similar_articles':similar_articles
    }
    return render(request, 'articles/article_detail.html', context)

@login_required
def article_share(request, article_id):
    # Retrieve post by id
    article = get_object_or_404(Articles, id=article_id, status=Articles.Status.PUBLISHED)
    sent = False
    
    if request.method == 'POST':
    # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            # ... send email
            article_url = request.build_absolute_uri(
            article.get_absolute_url())
            subject = f"{cd['name']} recommends you read " \
            f"{article.title}"
            message = f"Read {article.title} at {article_url}\n\n" \
            f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'your_account@gmail.com',
            [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'articles/share.html', {'article': article, 'form':form, 'sent':sent })

@require_POST
def article_comment(request, article_id):
    article = get_object_or_404(Articles, id=article_id, status=Articles.Status.PUBLISHED)
    comment = None
    
    # A comment was posted
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # Create a Comment object without saving it to the database
        comment = form.save(commit=False)
        # Assign the post to the comment
        comment.article = article
        # Save the comment to the database
        comment.save()
    return render(request, 'articles/comment.html', {
            'article': article, 
            'form': form, 
            'comment': comment
            })
    
    
def like_article(request, pk):
    article = get_object_or_404(Articles, id=pk)
    
    if article.author != request.user:    
        article.likes.add(request.user)
    return redirect('article', article.id)
def create_articles(request):
    if request.method == 'POST':
        form = ArticlesForm(request.POST, request.FILES or None)
        if form.is_valid():
            article = form.save(commit=False)
            article.author = request.user 
            article.save()
            messages.success(request, ('Successfully created article!'))
            return redirect('articles:articles_list')
        else:
            messages.info(request, 'something went wrong')
    else:
        form = ArticlesForm()
    return render(request,'articles/create.html',{'form':form})


def update_articles(request, pk):
    article = Articles.published.get(id=pk)
    form = ArticlesForm()
    if request.method == 'POST':
        form = ArticlesForm(request.POST, request.FILES, instance=article)
        if form.is_valid():
            form.save()
            return redirect('articles:articles_list')
    else:
        form = ArticlesForm(instance=article)
    return render(request, 'articles/update.html', {'form': form})
        
def delete_articles(request, pk):
    article = Articles.published.get(id=pk)
    if request.method == 'POST':
        article.delete()
        return redirect('articles:articles_list')


def books(request):
    YOUR_API_KEY = "AIzaSyAjmAgT3Q4tHYtSKiUkhpvw5sbVhEB765Y"
    if request.method == 'POST':
        form = SearchBook(request.POST)
        text = request.POST['text']
        url = f"https://www.googleapis.com/books/v1/volumes?q={text}&key={YOUR_API_KEY}"
        r = requests.get(url)
        answer = r.json()
        result_list = []
        for i in range(10):
            result_dict = {
                'title':answer['items'][i]['volumeInfo']['title'],
                'subtitle':answer['items'][i]['volumeInfo'].get('subtitle'),
                'thumbnail':answer['items'][i]['volumeInfo'].get('imageLinks').get('thumbnail'),
                'preview':answer['items'][i]['volumeInfo'].get('previewLink'),
            }
            result_list.append(result_dict)
            context = {
                'form': form,
                'results':result_list
            }
    
        return render(request, 'articles/books.html', context)  # Show error template
    else:
        url = f"https://www.googleapis.com/books/v1/volumes?q=programming&key={YOUR_API_KEY}"
        r = requests.get(url)
        answer = r.json()
        result_list = []
        for i in range(10):
            result_dict = {
                'title':answer['items'][i]['volumeInfo']['title'],
                'subtitle':answer['items'][i]['volumeInfo'].get('subtitle'),
                'thumbnail':answer['items'][i]['volumeInfo'].get('imageLinks').get('thumbnail'),
                'preview':answer['items'][i]['volumeInfo'].get('previewLink'),
            }
            result_list.append(result_dict)
        return render(request, 'articles/books.html', {'results':result_list})
    

inspiration/views.py
from django.shortcuts import render, get_object_or_404
from .models import Inspiration

# Create your views here.'

def inspiration(request):
    inspirations = Inspiration.objects.all()
    context = {
        'inspirations':inspirations
    }
    return render(request, 'articles/inspiration.html', context)

# def inspiration_detail(request, slug):
#     inspiration = get_object_or_404(Inspiration, slug=slug)
#     context = {
#         'inspiration':inspiration
#     }
#     return render(request, 'inspiration/inspiration.html', context)

templates/articles/all_articles.html
{% extends 'base.html' %}
{% load article_tags %}
{% load humanize %}
{% load static %}
{% block title %}Home page{% endblock %}
{% block content %}


  <section onclick="" class="search" id="articles">
      <h1>All Articles</h1>
      <form method="get" class="search__input ">
        <input type="text" name="title" placeholder="Search articles" />
        <button><i class="bx bxs-search"></i></button>
      </form>
    </section>

     <section class="article__section" >
      <!-- {% if tag %}
      <h2>Articles tagged with "{{ tag.name }}"</h2>
      {% endif %} -->
        {% for article in articles %}
      <article class="articles">
          <!-- {% for tag in article.tags.all %}
            <a style="text-decoration: none;" href="{% url 'articles:articles_list_by_tag' tag.slug %}">{{ tags.name }}</a>
            {% if not forloop.last %},{% endif %}
          {% endfor %} -->
        <h2>{{article.title}}</h2>
        <p>
          {{article.content|markdown|truncatewords:37|safe}}
        </p>
        <div class="articles__readmore">
          <a href="{{ article.get_absolute_url }}">Read more <i class="bx bx-chevrons-right"></i></a>
          <span>{{article.publish|naturaltime}}</span>
        </div>
      </article>
      {% empty %}
      <h1 style="text-align: center; color: #afafaf;">No Article with That Name...</h1>
      {% endfor %}
    </section>
    <div class="container  text-center my-5 mx-auto flex items-center">
      {%  include 'includes/pagination.html' with page=articles %}
    </div>
   

{% endblock %}

templates/articles/article-list.html
{% extends 'base.html' %}
{% load humanize %}
{% load article_tags %}
{% load static %}
{% block title %}Home page{% endblock %}
{% block content %}

    <section class="searcher" id="articles">
      <div class="searcher__left">
        <h1>Narrative</h1>
        <p>
          Your Number One Source for All Tech-Related News, In-Depth
          Tutorials, and Valuable Insights. We're Committed to Providing You
          with the Very Best Content, Enriched by Community Standards and
          Expertise. Get Ready to Dive into the World of Django Excellence!
        </p>
        <div class="searcher__btn">
          <a href="{% url 'articles:create_article' %}">Submit Project</a>
          <a href="{% url 'articles:all_articles' %}">Read articles</a>
        </div>
      </div>
      <div class="illustration">
        <img src="{% static '/images/illustration.png' %}" alt="illustration" />
      </div>
    </section>

    <section class="latest">
      <h2>Latest  Articles</h2>
      <P>Read the latest from Narrative</P>
    </section>

     <section class="article__section" >
      {% for article in articles %}
      <article class="articles">
        <button>DJANGO</button>
        <h2>{{article.title}}</h2>
        <p>
          {{article.content|truncatewords_html:37|safe}}
        </p>
        <div class="articles__readmore">
          <a href="{{ article.get_absolute_url }}">Read more <i class="bx bx-chevrons-right"></i></a>
          <span>{{article.publish|naturaltime}}</span>
        </div>
      </article>
      {% endfor %}
    </section>
     <div class="view-all">
      <button title="view all"><a href="{% url 'articles:all_articles' %}">View all</a></button>
    </div>

{% endblock %}

templates/articles/article_detail.html
{% extends 'base.html' %}
{% load article_tags %}
{% load humanize %}
{% load static %}
{% block title %}{{article.title}}{% endblock %}
{% block content %}
    <!-- Page Content --> 

    <style>
      .detail__articles pre{
        background: rgb(27, 27, 27);
        padding: 2rem;
        border-radius: 10px;
        code{
          color: aliceblue;
        }
      }
    </style>

    <section class="detail__articles">
      <h1>
        {{ article.title }}
      </h1>

      <div class="profile" onmouseover="display()" onmouseleave="noDisplay()">
        <img src="{{ article.author.profile.photo.url }}" alt="" />
        <div class="text__profile">
          <h4>{{article.author}} . <strong> Follow </strong></h4>
          <span>{{article.publish|naturaltime}} read | {{article.publish|naturalday}}</span>
        </div>
        <div class="hover">
          <div class="text__profile">
            <img src="{{ article.author.profile.photo.url }}" alt="" />
            <span>{{ article.author.username }}</span><br/>
          </div>
          <div class="text">

            {% if request.user.username == author.username %}
              <a href="#"><i class="fa-solid fa-user-plus"></i> Edit Article</a>
            <a href="#"><i class="fa-solid fa-user"></i> Edit Profile</a>
            {% else %}
            <a href="#"><i class="fa-solid fa-user-plus"></i> Follow</a>
            <a href="{% url 'profile' username=article.author.username %}"><i class="fa-solid fa-user"></i> View Profile</a>
            {% endif %}
          </div>
        </div>
      </div> 
      <div class="detail__appreciate">
        <div class="detail__left" id="like-container">
          <a  class="clap" href=""> 
            <i class="fa-solid fa-hands-clapping"></i>
             <span>{{ article.likes.count }}</span> </a>
          <a href="#comment">
            <i class="fa-regular fa-comment"></i>
          </a>
        </div>
        <div class="detail__right">
          <a href="#"><i class="fa-solid fa-bookmark"></i></a>
          <a href="{% url 'articles:article_share' article.id %}"><i class="fa-solid fa-share-from-square"></i></a>
          <a href="#"><i class="fa-solid fa-ellipsis-vertical"></i></a>
        </div>
      </div>
      <div class="detail__image">
        <!-- Assuming you have a variable named 'article' in your template context -->
          {% if article.image %}
              <img src="{{ article.image.url }}" alt="Article Image">
            {% else %}
                <p>No image available</p>
          {% endif %}
        <p >
         {{article.content|markdown|safe}}
        </p>

        <h3>Why Next.Js and Django?</h3>

        <p>
          While many web frameworks are available, both Next.js and Django are
          popular for web development due to their ease of use, flexibility, and
          robust feature sets. Next.js is a React-based framework that allows
          developers to build server-side rendered (SSR) and static websites
          easily. It provides a simple, intuitive development experience with
          automatic code splitting and optimized performance. Next.js also
          offers features such as file-based routing, API routes, and static
          site generation (SSG), which makes it an ideal choice for building
          modern web applications that require high-performance, SEO-friendly,
          and scalable front-ends. Django is a full-stack Python-based framework
          that provides an excellent toolset for building web applications.
          Django provides a powerful and flexible Object-Relational Mapping
          (ORM) system that allows developers to easily manage their data and a
          built-in admin panel that makes it easy to manage the application's
          Backend. Django also provides robust security features, such as CSRF
          protection and password hashing, making it a safe choice for building
          web applications. The combination of Next.js and Django offers a
          powerful development stack for building modern, scalable, and secure
          web applications. By using Next.js for the Frontend and Django for the
          Backend, developers can take advantage of the strengths of both
          frameworks to create a seamless, high-performance web application. For
          example, Next.js can handle the front-end routing, page transitions,
          and client-side interactions, while Django can manage the backend API
          endpoints, database management, and server-side rendering of pages.
          This allows for a clear separation of concerns between the
          application's front-end and back-end, making the codebase more
          maintainable and easier to scale.
        </p>
        <!-- detail reference -->
        <h5>References</h5>
        <span>
          Cabezas, I., Segovia, R., Caratozzolo, P., & Webb, E. (2020). Using
          Software Engineering Design Principles as Tools for Freshman Students
          Learning. 2020 IEEE Frontiers in Education Conference (FIE).
          <a href="#">https://doi.org/10.1109/fie44824.2020.9274177</a>
        </span>
      </div>
        <div class="comment__section">
        <div class="comment-session">
          <div class="post-comment">
            {% for comment in comments %}
            <div class="comment-list" id="comment">
              <div class="flex">
                <div class="user">
                  <div class="user-image">
                    <img src="{% static '/images/Asaiah Henson.jpg' %}" alt="">
                  </div>
                  <div class="user-media">
                    <div class="name">Asaiah</div>
                    <div class="day">{{comment.created|naturaltime}}</div>
                  </div>
                </div>
                <div class="reply">
                  {% with comments.count as total_comments %}
                  <div class="lick icon">
                    {{ total_comments }} comment{{ total_comments|pluralize }}
                  </div>
                  {% endwith %}
                  
                  <div class="dislick icon"><i class="fa-solid fa-thumbs-up"></i></div>
                  <div class="dislick icon"><i class="fa-solid fa-thumbs-down"></i></div>
                  <div class="re-comment">Reply</div>
                </div>
              </div>
              <div class="comment">
                <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
                </p>
                {{ comment.body|linebreaks|safe }}
              </div>
            </div>
            {% empty %}
            <p class="text">There are no comments.</p>
            {% endfor %}
            {% include 'includes/comment_form.html' %}
          </div>
        </div> 
      </div>
      <div class="profile__end">
        <div class="profile__left">
          <img src="{% static '/images/Asaiah Henson.jpg' %}" alt="" />
          <h3>Written by {{user.username}}</h3>
          <span>5 followers</span>
        </div>
        <div class="profile__right">
          <a href="#">Follow</a>
          <a href="#"><i class="fa-solid fa-envelope-open-text"></i></a>
        </div>
      </div>
      <div class="detail__more">
        <h4>Similar posts</h4>
        <div class="more__projects">
          {% for post in similar_articles %}
          <div class="more__card">
            <img class="more__imgage" src="{{ post.image.url }}" alt="" />
            <div class="more__image">
              <img src="{% static '/images/Asaiah Henson.jpg' %}" alt="" />
              <span>Asaiah Henson</span>
            </div>
            <h3>{{post.title}}</h3>
            <span>
              {{post.content|truncatewords:20|safe }}
            </span>
            <small>{{article.publish|naturaltime}}</small>
            <div class="detail__appreciate">
              <div class="detail__left">
                <a href="#"> <i class="fa-solid fa-hands-clapping"></i> 1 </a>
                <a href="#">
                  <i class="fa-regular fa-comment"></i>
                </a>
              </div>
              <div class="detail__right">
                <a href="#"><i class="fa-solid fa-bookmark"></i></a>
                <a href="#"><i class="fa-solid fa-share-from-square"></i></a>
                <a href="#"><i class="fa-solid fa-ellipsis-vertical"></i></a>
              </div>
            </div>
          </div>
          {% empty %}
         <h5 class="similar__articles">No Similar Articles Found!</h5> 
          {% endfor %}
        </div>
      </div>
    </section>
   {% endblock %}

templates/articles/books.html
{% extends 'base.html' %}
{% load article_tags %}
{% load humanize %}
{% load static %}
{% block title %}{{article.title}}{% endblock %}
{% block content %}
    <!-- Page Content --> 

    <style>
        .inspiration__wrapper{
            gap: 1rem;
        }
    </style>

  
    <section class="search" id="articles">
      <h1>Featured books</h1>
      <form method="POST" class="search__input ">
        {% csrf_token %}
        <input type="text" name="text" placeholder="Search Books" />
        <button><i class="bx bxs-search"></i></button>
      </form>
    </section>

    <section class="inspiration__wrapper">
        {% for result in results %}
        <div class="content">
            <div class="content__img">
                <img style="object-fit: cover; max-height: 300px;" src="{{ result.thumbnail }}" alt="">
            </div>
            <div class="content__detail">
                <span>OPEN SOURCE</span>
                <h3>{{ result.title }}</h3>
                    <p>By {{ result.subtitle }}</p>
                <a href="{{ result.preview }}" target="_blank">Know More <i class="bx bx-chevrons-right"></i></a>
            </div>
        </div>
        {% endfor %}
    </section>
   {% endblock %}

templates/articles/comment.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Comment Page {% endblock %}


{% block content %}

 {% if comment %}
 <section style="margin-top: 10rem;" class="comment__success">
     <h2>Your comment has been added.</h2>
     <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
</section>
     {% else %}

    {% include 'includes/comment_form.html' with form=form %}
 {% endif %}
{% endblock %}