accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('author/<str:username>/', views.user_profile, name='profile'),
    # login / logout urls
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('signup/', views.signup_user, name="signup"),
    path('edit/', views.edit, name='edit'),
    path('404/', views.custom_404, name="404"),
    path('password-change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password-reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path('', views.articles_list, name='articles_list'),
    path('tag/<slug:tag_slug>/', views.articles_list, name='articles_list_by_tag'),
    # path('add-like/<int:pk>/', views.add_like, name='add_like'),
    path('books', views.books, name='books'),
    path('article/<slug:article_id>/like', views.like_article, name="like"),
    path('all-articles/', views.all_articles, name='all_articles'),
    path('create-article/', views.create_articles, name='create_article'),
    path('update-article/<int:pk>/', views.update_articles, name='update_article'),
    path('<int:year>/<int:month>/<int:day>/<slug:article>/', views.articles_detail, name='articles_detail'),
    path('<int:article_id>/share/', views.article_share, name='article_share'),
    path('<int:article_id>/comment/', views.article_comment, name='article_comment'),
    path('delete-article/<int:pk>/', views.delete_articles, name='delete_articles'),
]

inspiration/urls.py
from django.urls import path
from .import views

app_name='inspiration'

urlpatterns = [
    path('inspiration/', views.inspiration, name='inspiration'),
    # path('inspiration-detail/', views.inspiration_detail, name='inspiration_detail')
]

narrative_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from articles.sitemaps import ArticleSitemap

sitemaps = {
    'articles': ArticleSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls', namespace='articles')),
    path('accounts/', include('accounts.urls')),
    path('inspiration/', include('inspiration.urls', namespace='inspiration')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
    ]

templates/base.html
<!DOCTYPE html>
{% load article_tags %}
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
      rel="stylesheet"
    />
    <script src="https://unpkg.com/htmx.org@1.9.10" integrity="sha384-D1Kt99CQMDuVetoL1lrYwg5t+9QdHe7NLX/SoJYkXDFfX37iInKRy5xLSi8nO7UC" crossorigin="anonymous"></script>
       <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/noty/3.1.4/noty.min.js">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/noty/3.1.4/noty.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/noty/3.1.4/noty.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/noty/3.1.4/noty.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://rsms.me/inter/inter.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link
      href="https://api.fontshare.com/v2/css?f[]=clash-grotesk@200,700,400,600,300,1,500&display=swap"
      rel="stylesheet"
    />
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.20/dist/summernote.min.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/summernote@0.8.20/dist/summernote.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar">
      <div class="navbar__left">
        <a href=".{% url 'articles:articles_list' %}">
          <img src="{% static 'images/logo.svg' %}" alt="" />
        </a>
        <button title="Toggle Dark Mode" id="icons">
          <i class="bx bxs-sun"></i>
        </button>
      </div>
      <div class="navbar__right">
          <ul>
              <li><a href="{% url 'articles:all_articles' %}">Articles</a></li>
              <li><a href="{% url 'inspiration:inspiration' %}">Inspiration</a></li>
              <li><a href="{% url 'articles:books' %}">Books</a></li>
              <li><a href="#">Podcasts</a></li>
              {% if user.is_authenticated %}
              <li><a href="{% url 'articles:create_article' %}" style="display: flex; align-items:center;">Write<i class='bx bxs-edit' style="margin-left: 8px;"></i></a></li>
              <li><a href="{% url 'logout' %}" style="display: flex; align-items:center;">logout<i class="fa-solid fa-right-to-bracket" style="margin-left: 8px;"></i></a></li>
          {% else %}
          <li><a href="{% url 'signup' %}" style="display: flex; align-items:center;">Get Start<i class="fa-solid fa-right-to-bracket" style="margin-left: 8px;"></i></a></li>
            {% endif %}
        </ul>
      </div>
      <div class="sidebar">
        <ul>
          <li onclick="CloseSidebar()"><i class="bx bx-x"></i></li>
          <li><a href="{% url 'articles:all_articles' %}">Articles</a></li>
          <li><a href="./Inspiration.html">Inspiration</a></li>
          <li><a href="#">Books</a></li>
          <li><a href="#">Podcasts</a></li>
          <li><a href="#">Courses</a></li>
          <li><a href="{% url 'articles:create_article' %}">Write</a></li>
        </ul>
      </div>
      <div onclick="OpenSidebar()" class="menu">
        <i class="bx bx-menu-alt-right"></i>
      </div>
    </nav>
{% block content %}

{% endblock%}
<script>
 var msg_levels = { 20: 'info', 25: 'success', 30: 'warning', 40: 'error' };
 
   {% if messages %}
     {% for msg in messages %}
       new Noty({
           type: msg_levels['{{msg.level}}'],
           text: '{{msg}}',
           timeout: 5000,
           theme: 'metroui'
       }).show();
     {% endfor %}
   {% endif %}

 
 

</script>

    <section class="footer">
      <div class="links">
        <ul>
          <li><a href="">Resources</a></li>
          <li><a href="">Sitemap</a></li>
          <li><a href="">RSS feed</a></li>
          <li><a href="">Featured request</a></li>
          <li><a href="">Report bug</a></li>
        </ul>
      </div>
      <div class="links">
        <ul>
          <li><a href="">Pages</a></li>
          <li><a href="">About us</a></li>
          <li><a href="">Contact us</a></li>
          <li><a href="">Privacy policy</a></li>
          <li><a href="">Terms and conditions</a></li>
        </ul>
      </div>
      <div class="links">
        <ul>
          <li><a href="">Explore</a></li>
          <li><a href="">Articles</a></li>
          <li><a href="">MadewithDjango</a></li>
          <li><a href="">Books</a></li>
          <li><a href="">Courses</a></li>
          <li><a href="">Notepad</a></li>
        </ul>
      </div>
      <div class="links">
        <ul>
          <li><a href="">MadewithDjango</a></li>
          <li><a href="">Submit a project</a></li>
          <li><a href="">Social Media</a></li>
          <li><a href="">Open Source projects</a></li>
          <li><a href="">Edtech</a></li>
          <li><a href="">Fintech</a></li>
        </ul>
      </div>
    </section>
    <button class="pointer">
      <a href="#articles"><i class="bx bx-up-arrow-alt"></i></a>
    </button>
    <section class="copyright">
      <a href="#">
        <img src="{% static 'images/logo.svg' %}" alt="" />
        Narrated
      </a>
      <span> &copy; 2024 Made with Django. All rights reserved. </span>
    </section>
    <script src="{% static 'js/scripts.js' %}"></script>
  </body>
</html>